apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-ms
  labels:
    app: cliente-ms
spec:
  selector:
    matchLabels:
      app: cliente-ms
  template:
    metadata:
      labels:
        app: cliente-ms
    spec:
      containers:
        - name: cliente-ms
          image: phillippimenta/cliente-ms
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8091
          envFrom:
            - secretRef:
                name: cliente-ms
          startupProbe:
            httpGet:
              port: http
              path: /actuator/health
            failureThreshold: 30
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi