apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cliente-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cliente-ms
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50